### ISSUE TITLE
Cannot Find Phoenix.Router, others in new Phoenix project.

### ISSUE THREAD

**Issue by Havvy** [vishnevskiy/ElixirSublime#5]
In Phoenix projects, `use Phoneix.X` gives a lint warning saying that it cannot find the proper module.

Steps to reproduce:

1. Download Phoenix has per their instructions.
1. mix phoenix.new Test /path/to/test
1. cd /path/to/test
1. mix deps.get
1. mix compile
1. subl /path/to/test/web/router.ex

See a red dot on line 2 with statement "Error: module Phoenix.Router is not loaded and cannot be found.

**Comment by rjsamson** [comment]
I'm getting this same issue on OSX Yosemite

**Comment by hiphoox** [comment]
yeah, I have the same problem with all my use statements. 

Example:   use Ecto.Repo, adapter: Ecto.Adapters.Postgres

I'm using Yosemite and I opened sublime in the project directory
![repo_ex_ _peopleware_and_cannot_find_phoenix_router__others_in_new_phoenix_project__ _issue__5_ _vishnevskiy_elixirsublime](https://cloud.githubusercontent.com/assets/17475/5675156/595c70ca-977d-11e4-8648-b9f5c80b55ba.png)

**Comment by andref** [comment]
I had the same issue and discovered that the [linter plugin](https://github.com/vishnevskiy/ElixirSublime/blob/caa9d21c9949346c986a116c8ad35b6d7fbc6d09/elixir_sublime.py#L317) cannot find the mix project. When `elixirc` runs, it doesn’t have a proper path where to find the modules.

That happens because `find_mix_project` uses `os.getcwd` if no argument is given as a starting point. However, there’s no guarantee that the current directory will be the phoenix project (in my case, it was the Sublime Text package folder or some such). I fixed it by changing elixir_sublime.py and feeding `find_mix_project` the file the linter is currently handling, `self.filename`:

```python
  class ElixirLinter(Linter):
      ...
      def cmd(self):
          ...
          for path in find_ebin_folders(find_mix_project(self.filename)):
              command.extend(['-pa', path])
```

I’m not sure if this will break other stuff since I never wrote a sublime linter plugin (and that’s why I’m not making a PR), but it works for me.

**Comment by andreionut** [comment]
That fixed it for me @andref 
I think you should put a PR

**Comment by Havvy** [comment]
Fixed by PR #13

**Comment by vladra** [comment]
I have same problem with `use Something.Web, :router` and all other uses of `use`. Any tips how to solve this?

**Comment by aawilson** [comment]
To @vladra and others: When I ran into this same issue, it wasn't due to ElixirSublime, but instead from the SublimeLinter elixirc plugin in a Mix context. The appropriate config for a Mix project for that plugin is specified here: https://github.com/smanolloff/SublimeLinter-contrib-elixirc#example
